spring.application.name=SpringBootWebDemo
server.port=8081

logging.file.name=logs/app.log
#logging.level.root=warn

management.endpoints.web.exposure.include=*

management.endpoints.web.base-path=/manage

management.endpoint.health.show-details=ALWAYS

spring.datasource.url=jdbc:mysql://localhost:3306/upgrad
spring.datasource.username=root
spring.datasource.password=root1234
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.output.ansi.enabled=ALWAYS